version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
    healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "--silent" ]
        interval: 10s
        retries: 5


  spring_app:
    image: oumaymajebali/oumaymajebali_g3_kaddem
    container_name: devopscontainer
    restart: on-failure
    ports:
      - 8083:8083
    depends_on:
      - mysqldb
