services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: tasnimnefzi/tasnimnefzi_g3_kaddem
    container_name: tasnimnefzi_g3_kaddem
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
