services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql

  spring_app:
    image: nerminemelkiamdouni/nerminemelkiamdouni_g3_kaddem
    container_name: nerminemelkiamdouni_g3_kaddem
    restart: on-failure
    ports:
      - 8083:8083
    depends_on:
      - mysqldb



